import requests
import re

url = "http://localhost:5000/api/reports/606dc003-3a84-4bb1-a34a-e16fd61425a0/html"
res = requests.get(url)
assert res.status_code == 200, f"Failed to get report: {res.status_code}"
html = res.text

# Split by .page-break
parts = html.split('<div class="page-break"></div>')
print(f"Total pages separated by page-break: {len(parts)}")
assert len(parts) == 3, f"Expected 3 pages, got {len(parts)}"

for i, p in enumerate(parts):
    print(f"\n=== PAGE {i+1} HEADINGS ===")
    clean_p = re.sub(r'data:image/[^;]+;base64,[A-Za-z0-9+/=]+', '', p)
    for line in clean_p.splitlines():
        if "section-title" in line or "header-title" in line:
            print("  ", line.strip())

page1, page2, page3 = parts[0], parts[1], parts[2]

# Page 1 checks
assert "CLINICAL SUMMARY" in page1
assert "Patient & Encounter Information" in page1
assert "REFER" in page1
assert "Grade 4" in page1
assert "Calibrated referral probability: 99.74%" in page1
assert "Original Fundus Image" in page1
assert "Enhanced Fundus Image" in page1
print("\nPage 1 validation: PASSED")

# Page 2 checks
assert "Why Did RETINOVA Flag This Image?" in page2
assert "Grad-CAM" in page2
assert "Areas contributing most strongly to the model prediction." in page2
assert "Retinal Vessel" in page2
assert "Candidate Lesion" in page2
assert "Candidate lesion evidence generated by morphological analysis for clinician review" in page2
assert "Composite Retinal Abnormality Map" in page2
assert "Key Findings" in page2
assert "NEOVASCULARIZATION ASSESSMENT" in page2
assert "Dedicated Assessment: <em>Not available</em>" in page2
assert "Recommended Clinical Action" in page2
print("Page 2 validation: PASSED")

# Page 3 checks
assert "Clinical Disposition" in page3
assert "Referral confirmed" in page3
assert "Referral not confirmed" in page3
assert "Recapture required" in page3
assert "Clinical follow-up recommended" in page3
assert "Clinician Notes:" in page3
assert "Recommended Follow-up:" in page3
assert "Final Clinical Grade:" in page3
assert "Reviewer Name:" in page3
assert "Registration / License Number:" in page3
assert "Signature:" in page3
assert "Clinical Disclaimer" in page3
assert "<details" in page3
assert "</details>" in page3
assert "Technical Details & Model Diagnostics" in page3
print("Page 3 validation: PASSED")

# Check technical leakage on Pages 1-3
pages1_2_3_visible = parts[0] + parts[1] + parts[2].split('<details', 1)[0]
clean_visible = re.sub(r'data:image/[^;]+;base64,[A-Za-z0-9+/=]+', '', pages1_2_3_visible)
clean_text = re.sub(r'<[^>]+>', ' ', clean_visible)

leaks = []
for term in ['1.4555', '0.2993', 'IoU', 'tensor', 'pytorch', 'branch-point']:
    if term.lower() in clean_text.lower():
        leaks.append(term)

print("\nTechnical terms leaked on visible clinical pages:", leaks)
assert len(leaks) == 0, f"Found leaked engineering terms: {leaks}"

print("\n=== ALL VISUAL REPORT & SAFETY CHECKS PASSED ===")
